import { afterEach, describe, expect, test } from "bun:test"
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { FileOrganizer, type FileBoundary, type FileCategory, type FilePlan } from "../src/files"
import { SoulStore } from "../src/store"

const roots: string[] = []
const stores: SoulStore[] = []
function fixture() {
  const root = mkdtempSync(join(tmpdir(), "xingyao-files-test-")); roots.push(root)
  const directory = join(root, "待整理 files"); mkdirSync(directory)
  const store = new SoulStore(join(root, "host", "domain.sqlite")); stores.push(store)
  return { root, directory, store, files: new FileOrganizer(store.db) }
}
function put(directory: string, name = "说明.txt", content = "只属于这个临时测试的原始内容") { const path = join(directory, name); writeFileSync(path, content); return path }
function interruptAt(store: SoulStore, boundary: FileBoundary) {
  return new FileOrganizer(store.db, { afterBoundary(step) { if (step === boundary) throw new Error(`simulated interruption: ${boundary}`) } })
}
function original(plan: FilePlan) { return join(plan.recoveryDirectory, `${plan.items[0]!.id}.original`) }
afterEach(() => {
  for (const store of stores.splice(0)) store.close()
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true })
})

describe("explicit directory previews", () => {
  test("classifies only direct regular files and leaves every file unchanged", async () => {
    const { directory, files, store } = fixture()
    const names = ["说明.txt", "photo.PNG", "song.mp3", "archive.tar.gz", "main.ts", "blob.bin"]
    for (const name of names) put(directory, name, name)
    put(directory, ".private.txt"); put(directory, "desktop.ini")
    mkdirSync(join(directory, "nested")); put(join(directory, "nested"), "never-scan.txt")
    const beforeRevision = store.revision
    const plan = await files.plan(directory)
    expect(plan.status).toBe("preview")
    expect(plan.items.map(item => item.category).sort()).toEqual((["文档", "图片", "音视频", "压缩包", "代码", "其他"] satisfies FileCategory[]).sort())
    expect(plan.skipped.map(item => item.name).sort()).toEqual([".private.txt", "desktop.ini", "nested"].sort())
    expect(existsSync(plan.recoveryDirectory)).toBe(false)
    expect(store.revision).toBe(beforeRevision + 1)
    for (const name of names) expect(readFileSync(join(directory, name), "utf8")).toBe(name)
    expect(files.get(plan.id)).toEqual(plan)
    expect(files.list().map(item => item.id)).toEqual([plan.id])
  })
  test("rejects relative roots and directory junctions; category junctions never receive files", async () => {
    const { root, directory, files } = fixture()
    const outside = join(root, "outside"); mkdirSync(outside)
    const rootLink = join(root, "root-link")
    symlinkSync(directory, rootLink, process.platform === "win32" ? "junction" : "dir")
    await expect(files.plan(rootLink)).rejects.toThrow("链接")
    await expect(files.plan(".")).rejects.toThrow("绝对")
    put(directory)
    symlinkSync(outside, join(directory, "文档"), process.platform === "win32" ? "junction" : "dir")
    const plan = await files.plan(directory)
    expect(plan.items).toHaveLength(0)
    expect(plan.skipped.some(item => item.name === "说明.txt" && item.reason.includes("链接"))).toBe(true)
    expect(readdirSync(outside)).toHaveLength(0)
  })
  test.skipIf(process.platform !== "win32")("excludes actual Windows hidden and system attributes", async () => {
    const { directory, files } = fixture()
    put(directory, "ordinary.txt")
    const protectedPath = put(directory, "protected.txt")
    const result = Bun.spawnSync(["attrib.exe", "+H", "+S", protectedPath], { windowsHide: true })
    expect(result.exitCode).toBe(0)
    const plan = await files.plan(directory)
    expect(plan.items.map(item => item.name)).toEqual(["ordinary.txt"])
    expect(plan.skipped.some(item => item.name === "protected.txt")).toBe(true)
  })
})

describe("verified moves and undo", () => {
  test("apply and undo are idempotent, preserve original content, and retain recovery originals", async () => {
    const { directory, files, store } = fixture()
    const source = put(directory), content = readFileSync(source, "utf8")
    const plan = await files.plan(directory)
    const done = await files.apply(plan.id)
    expect(done.status).toBe("completed")
    expect(existsSync(source)).toBe(false)
    expect(readFileSync(done.items[0]!.target, "utf8")).toBe(content)
    expect(readFileSync(original(done), "utf8")).toBe(content)
    const revision = store.revision
    expect(await files.apply(plan.id)).toEqual(done)
    expect(store.revision).toBe(revision)
    const undo = await files.undo(plan.id)
    expect(undo.status).toBe("undone")
    expect(readFileSync(source, "utf8")).toBe(content)
    expect(existsSync(done.items[0]!.target)).toBe(false)
    expect(readFileSync(original(done), "utf8")).toBe(content)
    const undoRevision = store.revision
    expect(await files.undo(plan.id)).toEqual(undo)
    expect(await files.apply(plan.id)).toEqual(undo)
    expect(store.revision).toBe(undoRevision)
  })
  test("does not overwrite an existing target even when its content is identical", async () => {
    const { directory, files } = fixture()
    const source = put(directory)
    mkdirSync(join(directory, "文档"))
    const target = put(join(directory, "文档"))
    const plan = await files.plan(directory)
    expect(plan.items[0]!.status).toBe("conflict")
    const result = await files.apply(plan.id)
    expect(result.status).toBe("partial")
    expect(result.items[0]!.status).toBe("conflict")
    expect(readFileSync(target, "utf8")).toBe(readFileSync(source, "utf8"))
    expect(existsSync(original(plan))).toBe(false)
  })
  test("source changes after preview stop the move before creating a target", async () => {
    const { directory, files } = fixture()
    const source = put(directory)
    const plan = await files.plan(directory)
    writeFileSync(source, "new user edits")
    const result = await files.apply(plan.id)
    expect(result.items[0]!.status).toBe("conflict")
    expect(readFileSync(source, "utf8")).toBe("new user edits")
    expect(existsSync(plan.items[0]!.target)).toBe(false)
  })
  test("a target directory replaced by a junction after preview receives nothing", async () => {
    const { root, directory, files } = fixture()
    const source = put(directory)
    const plan = await files.plan(directory)
    const outside = join(root, "outside"); mkdirSync(outside)
    symlinkSync(outside, join(directory, "文档"), process.platform === "win32" ? "junction" : "dir")
    const result = await files.apply(plan.id)
    expect(result.items[0]!.status).toBe("conflict")
    expect(existsSync(source)).toBe(true)
    expect(readdirSync(outside)).toHaveLength(0)
  })
  test("undo keeps both a new source and edited organized target unchanged", async () => {
    const { directory, files } = fixture()
    const source = put(directory)
    const plan = await files.plan(directory)
    const moved = await files.apply(plan.id)
    writeFileSync(source, "new source, never overwrite")
    const conflict = await files.undo(plan.id)
    expect(conflict.status).toBe("partial")
    expect(conflict.items[0]!.status).toBe("conflict")
    expect(readFileSync(source, "utf8")).toBe("new source, never overwrite")
    expect(existsSync(moved.items[0]!.target)).toBe(true)
    writeFileSync(moved.items[0]!.target, "edited target, never delete")
    const again = await files.undo(plan.id)
    expect(again.status).toBe("partial")
    expect(readFileSync(moved.items[0]!.target, "utf8")).toBe("edited target, never delete")
    expect(readFileSync(original(plan), "utf8")).toBe("只属于这个临时测试的原始内容")
  })
  test("undo of a preview cancels it without creating a recovery directory", async () => {
    const { directory, files } = fixture()
    const source = put(directory), plan = await files.plan(directory)
    expect((await files.undo(plan.id)).status).toBe("undone")
    expect(existsSync(source)).toBe(true)
    expect(existsSync(plan.recoveryDirectory)).toBe(false)
  })
  test("simultaneous apply calls cannot copy or archive the same file twice", async () => {
    const { directory, files, store } = fixture()
    put(directory)
    const plan = await files.plan(directory)
    const first = files.apply(plan.id)
    await expect(new FileOrganizer(store.db).apply(plan.id)).rejects.toThrow("正在进行")
    expect((await first).status).toBe("completed")
    expect(readdirSync(plan.recoveryDirectory)).toHaveLength(1)
  })
})

describe("interrupted file operation recovery", () => {
  test("a target created before ownership commit remains unknown; identical bytes cannot establish ownership", async () => {
    const { directory, files, store } = fixture()
    const source = put(directory), plan = await files.plan(directory)
    await expect(interruptAt(store, "target-created").apply(plan.id)).rejects.toThrow("interruption")
    const pending = files.get(plan.id)!
    expect(pending.items[0]!.phase).toBe("copying")
    expect(pending.items[0]!.targetIdentity).toBeUndefined()
    writeFileSync(pending.items[0]!.target, readFileSync(source))
    const resumed = await new FileOrganizer(store.db).apply(plan.id)
    expect(resumed.items[0]!.status).toBe("unknown")
    expect(existsSync(source)).toBe(true)
    expect(existsSync(original(plan))).toBe(false)
  })
  test("a fully verified owned copy resumes after the copy commit boundary", async () => {
    const { directory, files, store } = fixture()
    const source = put(directory), plan = await files.plan(directory)
    await expect(interruptAt(store, "copy-verified").apply(plan.id)).rejects.toThrow("interruption")
    expect(existsSync(source)).toBe(true)
    expect(files.get(plan.id)!.items[0]!.targetIdentity).toBeDefined()
    const resumed = await new FileOrganizer(store.db).apply(plan.id)
    expect(resumed.status).toBe("completed")
    expect(existsSync(source)).toBe(false)
    expect(readFileSync(original(plan), "utf8")).toBe("只属于这个临时测试的原始内容")
  })
  test("source archive interrupted before ledger commit is reconciled from identity and hashes", async () => {
    const { directory, files, store } = fixture()
    const source = put(directory), plan = await files.plan(directory)
    await expect(interruptAt(store, "source-archived").apply(plan.id)).rejects.toThrow("interruption")
    expect(existsSync(source)).toBe(false)
    expect(files.get(plan.id)!.items[0]!.phase).toBe("removing")
    expect((await new FileOrganizer(store.db).apply(plan.id)).status).toBe("completed")
    expect((await files.undo(plan.id)).status).toBe("undone")
    expect(existsSync(source)).toBe(true)
  })
  test("changed owned copies after interruption never cause removal of the source", async () => {
    const { directory, files, store } = fixture()
    const source = put(directory), plan = await files.plan(directory)
    await expect(interruptAt(store, "copy-verified").apply(plan.id)).rejects.toThrow("interruption")
    writeFileSync(plan.items[0]!.target, "outside edit of pending copy")
    const resumed = await files.apply(plan.id)
    expect(resumed.items[0]!.status).toBe("conflict")
    expect(existsSync(source)).toBe(true)
    expect(readFileSync(plan.items[0]!.target, "utf8")).toBe("outside edit of pending copy")
  })
  test("identical content in a replacement target does not prove that the replacement belongs to the plan", async () => {
    const { directory, files, store } = fixture()
    const source = put(directory), plan = await files.plan(directory)
    await expect(interruptAt(store, "copy-verified").apply(plan.id)).rejects.toThrow("interruption")
    // Keep the original inode alive so the replacement cannot coincidentally reuse it.
    const retained = join(directory, "retained-copy.txt")
    const { renameSync } = await import("node:fs")
    renameSync(plan.items[0]!.target, retained)
    writeFileSync(plan.items[0]!.target, readFileSync(source))
    const resumed = await files.apply(plan.id)
    expect(resumed.items[0]!.status).toBe("conflict")
    expect(existsSync(source)).toBe(true)
    expect(existsSync(retained)).toBe(true)
    expect(existsSync(original(plan))).toBe(false)
  })
  test("undo can resume after restore verification and after target archive", async () => {
    const { directory, files, store } = fixture()
    const source = put(directory), plan = await files.plan(directory)
    await files.apply(plan.id)
    await expect(interruptAt(store, "restore-verified").undo(plan.id)).rejects.toThrow("interruption")
    expect(existsSync(source)).toBe(true)
    expect(existsSync(plan.items[0]!.target)).toBe(true)
    await expect(interruptAt(store, "target-archived").undo(plan.id)).rejects.toThrow("interruption")
    expect(files.get(plan.id)!.items[0]!.phase).toBe("undo-removing")
    expect((await new FileOrganizer(store.db).undo(plan.id)).status).toBe("undone")
    expect(readFileSync(source, "utf8")).toBe("只属于这个临时测试的原始内容")
  })
  test("recovery directory without a committed ownership record blocks every move", async () => {
    const { directory, files, store } = fixture()
    const source = put(directory), plan = await files.plan(directory)
    await expect(interruptAt(store, "recovery-created").apply(plan.id)).rejects.toThrow("interruption")
    const result = await files.apply(plan.id)
    expect(result.status).toBe("partial")
    expect(result.error).toContain("所有权")
    expect(existsSync(source)).toBe(true)
    expect(existsSync(plan.items[0]!.target)).toBe(false)
  })
})
