import { chromium } from '@playwright/test'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

const host = process.argv[2]
if (!host) throw new Error('Pass the isolated development host directory')
const screenshotRoot = process.argv[3] ?? 'F:/codex/design'
mkdirSync(screenshotRoot, { recursive: true })
const running = JSON.parse(readFileSync(join(host, 'running.json'), 'utf8'))
const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 960 }, deviceScaleFactor: 1 })
const errors = []
page.on('pageerror', error => errors.push(error.message))
try {
  await page.goto(running.url)
  await page.getByRole('heading', { name: '对话与任务', exact: true }).waitFor()
  await page.waitForFunction(() => document.querySelector('#version').textContent.includes('0.1.0'))
  await page.locator('.nav[data-view="memory"]').click()
  await page.locator('#memory-form textarea').fill('浏览器验收：先给结论，再给依据。')
  await page.locator('#memory-form button').click()
  await page.locator('.memory-card').filter({ hasText: '浏览器验收' }).first().waitFor()
  await page.locator('.memory-card').filter({ hasText: '浏览器验收' }).first().getByRole('button', { name: '纠正' }).click()
  await page.locator('#edit-form textarea').fill('浏览器验收：回答清楚完整，并给出处。')
  await page.getByRole('button', { name: '保存纠正' }).click()
  await page.locator('.memory-card').filter({ hasText: '回答清楚完整' }).waitFor()
  await page.locator('.nav[data-view="knowledge"]').click()
  const source = join(host, 'ui-check-source.md')
  writeFileSync(source, '# 浏览器验收资料\n星杳通过来源追踪防止重复学习。\n', 'utf8')
  await page.locator('#knowledge-form input[name="path"]').fill(source)
  await page.getByRole('button', { name: '导入资料', exact: true }).click()
  await page.locator('.document-card').filter({ hasText: 'ui-check-source.md' }).waitFor()
  await page.locator('#knowledge-search').fill('重复学习')
  await page.locator('#search-knowledge').click()
  await page.locator('#knowledge-results').getByText('星杳通过来源追踪防止重复学习。', { exact: false }).waitFor()
  await page.locator('.nav[data-view="skills"]').click()
  await page.getByRole('heading', { name: '经验技能', exact: true }).waitFor()
  await page.locator('#skill-form').waitFor()
  await page.locator('#skill-list').getByText('这里保留可复用的方法。没有足够证据时，会明确保持待验证。').waitFor()
  await page.locator('.nav[data-view="sleep"]').click()
  await page.locator('#run-sleep').click()
  await page.locator('.report-card').first().waitFor()
  await page.locator('.nav[data-view="files"]').click()
  const folder = join(host, 'ui-files')
  mkdirSync(folder, { recursive: true })
  writeFileSync(join(folder, 'readme.txt'), '浏览器文件整理验收', 'utf8')
  await page.locator('#files-form input').fill(folder)
  await page.getByRole('button', { name: '生成整理预览' }).click()
  await page.locator('.file-plan').first().waitFor()
  await page.locator('.file-plan').first().getByRole('button', { name: '按清单整理' }).click()
  await page.locator('.file-plan').first().getByRole('button', { name: '撤销整理' }).waitFor()
  await page.locator('.file-plan').first().getByRole('button', { name: '撤销整理' }).click()
  await page.locator('.file-plan').first().getByText(/undone/).first().waitFor()
  await page.locator('#checkpoint').click()
  await page.getByText('检查点已验证并保存到 U 盘。').waitFor()
  await page.locator('.nav[data-view="system"]').click()
  await page.locator('#model-form').waitFor()
  await page.locator('#system-cards').getByRole('heading', { name: '执行引擎' }).waitFor()
  await page.locator('.nav[data-view="chat"]').click()
  await page.evaluate(() => document.querySelector('#notice').classList.add('hidden'))
  await page.mouse.move(1400, 20)
  await page.screenshot({ path: join(screenshotRoot, 'xingyao-first-build.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: join(screenshotRoot, 'xingyao-mobile-check.png'), fullPage: true })
  if (await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)) throw new Error('Mobile horizontal overflow')
  if (errors.length) throw new Error(errors.join('\n'))
  console.log(JSON.stringify({ browser: 'Microsoft Edge', result: 'passed', checked: ['navigation','memory create/correct','knowledge import/search','skills form/empty state','sleep','file plan/apply/undo','checkpoint','system/model settings','mobile layout'], pageErrors: errors.length }))
} finally { await browser.close() }
